### ISSUE TITLE
ValueError: invalid literal for int() with base 16: 'tcp'

### ISSUE THREAD

**Issue by philippludwig** [LunarEclipse363/brother_ql_next#2]
It seems that this fork somehow broke the print example in the README. 

```
brother_ql -m QL-820NWB -p tcp://192.168...... print -l 62 bitmap.png
```

This worked fine with the original version. With this fork, it yields:

```
Traceback (most recent call last):
  File "/home/philipp/.local/bin/brother_ql", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/philipp/.local/lib/python3.11/site-packages/brother_ql/cli.py", line 199, in print_cmd
    send(instructions=instructions, printer_identifier=printer, backend_identifier=backend, blocking=True)
  File "/home/philipp/.local/lib/python3.11/site-packages/brother_ql/backends/helpers.py", line 57, in send
    printer = BrotherQLBackend(printer_identifier)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/philipp/.local/lib/python3.11/site-packages/brother_ql/backends/pyusb.py", line 78, in __init__
    vendor, product = int(vendor, 16), int(product, 16)
                      ^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 16: 'tcp'
```

It seems that the code misinterprets the `tcp://` url now as a usb identifier, but I am not sure why.

**Comment by LunarEclipse363** [comment]
Ah, for some reason the code applied a default value of "pyusb" for the backend if none was specified, instead of using the backend autodetection function.

As a workaround, you can explicitly pass `-b network` or set the `BROTHER_QL_BACKEND=network` envar.

This will be fixed in the next release, thank you for the report!
